const TYPE_INFO = 'INFO';
const TYPE_POSTS = 'POSTS';
const TYPE_STATUS = 'STATUS';

const WORKER_INIT_SUCCESS = 'WORKER_INIT_SUCCESS';

export { TYPE_INFO, TYPE_POSTS, TYPE_STATUS, WORKER_INIT_SUCCESS };
